spring.application.name=e-commerce

spring.datasource.url = jdbc:mysql://localhost:3306/e_commerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# address and settigns(ssl, timezone)

spring.datasource.username= root
spring.datasource.password= 123456
# username and password for entering mysql

spring.jpa.hibernate.ddl-auto=update
#synchronizes db with the code

spring.jpa.show-sql=true
#makes sql commands visible in the intellij console

spring.jpa.properties.hibernate.format_sql=true
#for a tidy look

spring.web.error.include-message=always
#enables us to see the error message in postman

spring.jackson.deserialization.fail-on-unknown-properties=true
#if an unknown field comes throw exception and stop the app